---
apiVersion: v1
kind: Secret
metadata:
  name: csp-rest-secret
  labels:
    app: csp-rest
type: Opaque
stringData:
  API_KEY: c042ee2fa0f5bd5a3bceeae6f5cd8de066d6d9b9fd7
  KEY_THUMBPRINT: 3ad53bb2cfdc3f7b52dc9b827f7be56cece74537
  KEY_PASSWORD: "12345678"
  LICENSE_KEY: 40406-A0000-0219M-Q778D-1Y222
