{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "cryptopro-rest.fullname" .) }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptopro-rest.fullname" . }}
  annotations:
  {{- if eq .Values.secret.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "cryptopro-rest.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ randAlphaNum 64 | quote }}
  KEY_THUMBPRINT: {{ randAlphaNum 32 | quote }}
  CONTAINER: \\.\HDIMAGE\123
  KEY_PASSWORD: "1234567890"
  # LICENSE_KEY: ""
{{- end }}